Part way through work to add static classes to add fields.
Part way through changing all fieldnames to enums...

Currently not working (with tomcat) due to:
java.lang.NoClassDefFoundError: Could not initialize class com.stuartwarren.logit.fields.ExceptionField
    at com.stuartwarren.logit.jul.Layout.exceptionInformation(Layout.java:127)

Too tired to work it out at the mo.